name: incinerator
piecehammer: Hammer
m_name: $piece_incinerator
sizeMultiplier: 1
m_description: ''
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_workbench
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
notOnWood: false
wearNTearData:
  health: 1000
  damageModifiers:
    m_blunt: Resistant
    m_slash: Resistant
    m_pierce: Resistant
    m_chop: Resistant
    m_pickaxe: Resistant
    m_fire: Resistant
    m_frost: Resistant
    m_lightning: Immune
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
  materialType: Iron
craftingStationData: 
cSExtensionData: 
cSExtensionDataList: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData:
  defaultDrop: Coal
  defaultCostPerDrop: 10
  incineratorConversion:
  - Result: Coal
    ResultAmount: 1
    Priority: 0
    RequireOnlyOne: true
    Requirements:
    - Name: Wood
      Amount: 5
    - Name: ElderBark
      Amount: 5
    - Name: FineWood
      Amount: 5
    - Name: RoundLog
      Amount: 5
    - Name: YggdrasilWood
      Amount: 5
  - Result: Coal
    ResultAmount: 1
    Priority: 1
    RequireOnlyOne: true
    Requirements:
    - Name: TrophyBlob
      Amount: 1
    - Name: TrophyBoar
      Amount: 1
    - Name: TrophyBonemass
      Amount: 1
    - Name: TrophyDeathsquito
      Amount: 1
    - Name: TrophyDeer
      Amount: 1
    - Name: TrophyDragonQueen
      Amount: 1
    - Name: TrophyDraugr
      Amount: 1
    - Name: TrophyDraugrElite
      Amount: 1
    - Name: TrophyDraugrFem
      Amount: 1
    - Name: TrophyEikthyr
      Amount: 1
    - Name: TrophyFenring
      Amount: 1
    - Name: TrophyForestTroll
      Amount: 1
    - Name: TrophyFrostTroll
      Amount: 1
    - Name: TrophyGoblin
      Amount: 1
    - Name: TrophyGoblinBrute
      Amount: 1
    - Name: TrophyGoblinKing
      Amount: 1
    - Name: TrophyGoblinShaman
      Amount: 1
    - Name: TrophyHatchling
      Amount: 1
    - Name: TrophyLeech
      Amount: 1
    - Name: TrophyLox
      Amount: 1
    - Name: TrophyNeck
      Amount: 1
    - Name: TrophySerpent
      Amount: 1
    - Name: TrophySGolem
      Amount: 1
    - Name: TrophySkeleton
      Amount: 1
    - Name: TrophySkeletonPoison
      Amount: 1
    - Name: TrophySurtling
      Amount: 1
    - Name: TrophyTheElder
      Amount: 1
    - Name: TrophyWolf
      Amount: 1
    - Name: TrophyWraith
      Amount: 1
    - Name: TrophyGreydwarf
      Amount: 1
    - Name: TrophyGreydwarfBrute
      Amount: 1
    - Name: TrophyGreydwarfShaman
      Amount: 1
    - Name: TrophyGrowth
      Amount: 1
    - Name: TrophyUlv
      Amount: 1
    - Name: TrophyCultist
      Amount: 1
    - Name: TrophyAbomination
      Amount: 1
    - Name: TrophyTick
      Amount: 1
    - Name: TrophySeeker
      Amount: 1
    - Name: TrophySeekerBrute
      Amount: 1
    - Name: TrophyGjall
      Amount: 1
    - Name: TrophyDvergr
      Amount: 1
    - Name: TrophyHare
      Amount: 1
  - Result: Coal
    ResultAmount: 1
    Priority: 1
    RequireOnlyOne: true
    Requirements:
    - Name: ArrowBronze
      Amount: 20
    - Name: ArrowFire
      Amount: 20
    - Name: ArrowFlint
      Amount: 20
    - Name: ArrowFrost
      Amount: 20
    - Name: ArrowIron
      Amount: 20
    - Name: ArrowNeedle
      Amount: 20
    - Name: ArrowObsidian
      Amount: 20
    - Name: ArrowPoison
      Amount: 20
    - Name: ArrowSilver
      Amount: 20
    - Name: ArrowWood
      Amount: 20
    - Name: ArrowCarapace
      Amount: 20
    - Name: BoltBone
      Amount: 20
    - Name: BoltBlackmetal
      Amount: 20
    - Name: BoltCarapace
      Amount: 20
fireplaceData: 
teleportWorldData: 
plantData: 
shipData: 
build:
- Tin:8:1:True
- Copper:4:1:True
- SurtlingCore:1:1:True
