# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

# You can optionally change the color of your server name. Does not work for the address and port. Also, can show PvP status.
<color=red>SlowHeim Server</color>:
  address: 74.63.236.154
  port: 5914
  password: SlowHeim25
  iscrossplay: false
  ispvp: true



