## Tamed animal sizes
rae_OdinHorse:
 tamed:
  size: 0
Razorback_TW:
 tamed:
  size: 0
BlackBear_TW:
 tamed:
  size: 0
GrizzlyBear_TW:
 tamed:
  size: 0
Prowler_TW:
 tamed:
  size: 0
Lox:
 tamed:
  size: 0