{
	"TrophyNeck": 60
},
{
	"TrophyDeer": 120
},
{
	"TrophyTroll": 240
},
{
	"TrophySerpent": 360
},
{
	"TrophyEikthyr": 500
},
{
	"TrophyTheElder": 700
},
{
	"TrophyBonemass": 900
},
{
	"TrophyDragonQueen": 1100
},
{
	"TrophyGoblinKing": 1300
},
{
	"TrophySeekerQueen": 1500
},
{
	"TrophyFader": 1600
}