1:
  success: 87
2:
  success: 82
3:
  success: 77
4:
  success: 67
5:
  success: 62
6:
  success: 57
7:
  success: 47
8:
  success: 42
9:
  success: 37
10:
  success: 33
11:
  success: 29
12:
  success: 25
13:
  success: 21
14:
  success: 17
15:
  success: 14
16:
  success: 12
17:
  success: 10
18:
  success: 8
19:
  success: 7
