- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_S
    amount: 1
  Items:
  - AtgeirHimminAfl
  - AxeJotunBane
  - BowSpineSnap
  - PickaxeBlackMetal
  - ShieldCarapace
  - ShieldCarapaceBuckler
  - SledgeDemolisher
  - SpearCarapace
  - StaffFireball
  - StaffIceShards
  - StaffShield
  - StaffSkeleton
  - SwordMistwalker
  - THSwordKrom
  - CrossbowArbalest
  - SwordCheat
  - KnifeSkollAndHati
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_S
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_S
    amount: 1
  Items:
  - ArmorCarapaceChest
  - ArmorCarapaceLegs
  - ArmorMageChest
  - ArmorMageLegs
  - CapeFeather
  - HelmetCarapace
  - HelmetMage
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_A
    amount: 1
  Items:
  - AtgeirBlackmetal
  - AxeBlackMetal
  - KnifeBlackMetal
  - ShieldBlackmetal
  - ShieldBlackmetalTower
  - SwordBlackmetal
  - MaceNeedle
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_A
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_A
    amount: 1
  Items:
  - CapeLinen
  - CapeLox
  - ArmorPaddedGreaves
  - HelmetPadded
  - ArmorPaddedCuirass
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_B
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_B
    amount: 1
  Items:
  - BattleaxeCrystal
  - BowDraugrFang
  - FistFenrirClaw
  - KnifeSilver
  - MaceSilver
  - ShieldSilver
  - SpearWolfFang
  - SwordSilver
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_B
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_B
    amount: 1
  Items:
  - ArmorWolfChest
  - ArmorWolfLegs
  - CapeWolf
  - HelmetDrake
  - ArmorFenringChest
  - ArmorFenringLegs
  - HelmetFenring
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_C
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_C
    amount: 1
  Items:
  - AtgeirIron
  - AxeIron
  - Battleaxe
  - BowHuntsman
  - Lantern
  - MaceIron
  - PickaxeIron
  - ShieldBanded
  - ShieldIronBuckler
  - ShieldIronSquare
  - ShieldIronTower
  - ShieldSerpentscale
  - SledgeIron
  - SpearElderbark
  - SwordIron
  - TankardAnniversary
  - TorchMist
  - KnifeChitin
  - SpearChitin
  - ArmorRootChest
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_C
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_C
    amount: 1
  Items:
  - ArmorIronChest
  - ArmorIronLegs
  - ArmorRootLegs
  - HelmetIron
  - HelmetRoot
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_D
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_D
    amount: 1
  Items:
  - AtgeirBronze
  - AxeBronze
  - Cultivator
  - MaceBronze
  - PickaxeBronze
  - ShieldBronzeBuckler
  - SpearBronze
  - SwordBronze
  - BowFineWood
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_D
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_D
    amount: 1
  Items:
  - ArmorBronzeChest
  - ArmorBronzeLegs
  - ArmorTrollLeatherChest
  - ArmorTrollLeatherLegs
  - CapeTrollHide
  - HelmetBronze
  - HelmetTrollLeather
- enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_F
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Weapon_Blessed_F
    amount: 1
  Items:
  - AxeFlint
  - Bow
  - Hoe
  - KnifeButcher
  - KnifeCopper
  - KnifeFlint
  - PickaxeAntler
  - PickaxeStone
  - ShieldBoneTower
  - ShieldWood
  - ShieldWoodTower
  - SpearFlint
  - SledgeStagbreaker
- enchant_prefab:
    prefab: kg_EnchantScroll_Armor_F
    amount: 1
  blessed_enchant_prefab:
    prefab: kg_EnchantScroll_Armor_Blessed_F
    amount: 1
  Items:
  - ArmorLeatherChest
  - ArmorLeatherLegs
  - CapeDeerHide
  - HelmetLeather
  - ArmorRagsChest
  - ArmorRagsLegs
