- m_requirements:
  - m_prefabName: Wood
    m_amount: 5
  - m_prefabName: ElderBark
    m_amount: 5
  - m_prefabName: FineWood
    m_amount: 5
  - m_prefabName: RoundLog
    m_amount: 5
  - m_prefabName: YggdrasilWood
    m_amount: 5
  m_result: Coal
  m_resultAmount: 1
  m_requireOnlyOneIngredient: true
  m_priority: 0
- m_requirements:
  - m_prefabName: TrophyBlob
    m_amount: 1
  - m_prefabName: TrophyBoar
    m_amount: 1
  - m_prefabName: TrophyBonemass
    m_amount: 1
  - m_prefabName: TrophyDeathsquito
    m_amount: 1
  - m_prefabName: TrophyDeer
    m_amount: 1
  - m_prefabName: TrophyDragonQueen
    m_amount: 1
  - m_prefabName: TrophyDraugr
    m_amount: 1
  - m_prefabName: TrophyDraugrElite
    m_amount: 1
  - m_prefabName: TrophyDraugrFem
    m_amount: 1
  - m_prefabName: TrophyEikthyr
    m_amount: 1
  - m_prefabName: TrophyFenring
    m_amount: 1
  - m_prefabName: TrophyForestTroll
    m_amount: 1
  - m_prefabName: TrophyFrostTroll
    m_amount: 1
  - m_prefabName: TrophyGoblin
    m_amount: 1
  - m_prefabName: TrophyGoblinBrute
    m_amount: 1
  - m_prefabName: TrophyGoblinKing
    m_amount: 1
  - m_prefabName: TrophyGoblinShaman
    m_amount: 1
  - m_prefabName: TrophyHatchling
    m_amount: 1
  - m_prefabName: TrophyLeech
    m_amount: 1
  - m_prefabName: TrophyLox
    m_amount: 1
  - m_prefabName: TrophyNeck
    m_amount: 1
  - m_prefabName: TrophySerpent
    m_amount: 1
  - m_prefabName: TrophySGolem
    m_amount: 1
  - m_prefabName: TrophySkeleton
    m_amount: 1
  - m_prefabName: TrophySkeletonPoison
    m_amount: 1
  - m_prefabName: TrophySurtling
    m_amount: 1
  - m_prefabName: TrophyTheElder
    m_amount: 1
  - m_prefabName: TrophyWolf
    m_amount: 1
  - m_prefabName: TrophyWraith
    m_amount: 1
  - m_prefabName: TrophyGreydwarf
    m_amount: 1
  - m_prefabName: TrophyGreydwarfBrute
    m_amount: 1
  - m_prefabName: TrophyGreydwarfShaman
    m_amount: 1
  - m_prefabName: TrophyGrowth
    m_amount: 1
  - m_prefabName: TrophyUlv
    m_amount: 1
  - m_prefabName: TrophyCultist
    m_amount: 1
  - m_prefabName: TrophyAbomination
    m_amount: 1
  - m_prefabName: TrophyTick
    m_amount: 1
  - m_prefabName: TrophySeeker
    m_amount: 1
  - m_prefabName: TrophySeekerBrute
    m_amount: 1
  - m_prefabName: TrophyGjall
    m_amount: 1
  - m_prefabName: TrophyDvergr
    m_amount: 1
  - m_prefabName: TrophyHare
    m_amount: 1
  m_result: Coal
  m_resultAmount: 1
  m_requireOnlyOneIngredient: true
  m_priority: 1
- m_requirements:
  - m_prefabName: ArrowBronze
    m_amount: 20
  - m_prefabName: ArrowFire
    m_amount: 20
  - m_prefabName: ArrowFlint
    m_amount: 20
  - m_prefabName: ArrowFrost
    m_amount: 20
  - m_prefabName: ArrowIron
    m_amount: 20
  - m_prefabName: ArrowNeedle
    m_amount: 20
  - m_prefabName: ArrowObsidian
    m_amount: 20
  - m_prefabName: ArrowPoison
    m_amount: 20
  - m_prefabName: ArrowSilver
    m_amount: 20
  - m_prefabName: ArrowWood
    m_amount: 20
  - m_prefabName: ArrowCarapace
    m_amount: 20
  - m_prefabName: BoltBone
    m_amount: 20
  - m_prefabName: BoltBlackmetal
    m_amount: 20
  - m_prefabName: BoltCarapace
    m_amount: 20
  m_result: Coal
  m_resultAmount: 1
  m_requireOnlyOneIngredient: true
  m_priority: 1
